### ISSUE TITLE
Suggestions | Constituency homepage | Scheme performance snapshots

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#10]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/64309749/198519409-3adf209c-8ac5-439b-af2a-36ebfc20c576.png">

1. Can we make the latest financial year as the default view?

2. Can we club all the schemes for which data is available, together? (in this example, every scheme with data is followed by a scheme without data). 

Thoughts @samwhocodes @gggodhwani

**Comment by arunsud** [comment]
CBGA has suggested 2020-21 as the default year

**Comment by tauseefsshah** [comment]
Default year issue is fixed.
The schemes are clubbed together but here are still some indicator for which the data is not available.
