### ISSUE TITLE
Map only showing one colour whereas legand has multiple values

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#102]
![ffb118e1-00f0-4b58-a15e-a6d5e61395a6](https://user-images.githubusercontent.com/67921422/221206430-ad7b0d77-4a9e-4b6b-bc76-6845578b8521.JPG)

**Comment by aashimgarg** [comment]
![Screenshot from 2023-02-24 20-40-21](https://user-images.githubusercontent.com/55639487/221214252-bf71900e-ff04-4aa3-9817-043a464e18c0.png)

![Screenshot from 2023-02-24 20-40-39](https://user-images.githubusercontent.com/55639487/221214283-734c5a35-800f-4d06-910f-b23547f6752c.png)

This is not an issue, but rather a result of the nature of the data. @samwhocodes
