### ISSUE TITLE
Demarcation between common indicators and unique indicators

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#15]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/64309749/198523914-561cc5ca-e0a8-472c-94ef-4b7cd4744820.png">

Can we have some indication that the top ones are common indicators and the bottom ones are unique (scheme specific indicators)? Any suggestions on how to implement this? @samwhocodes @gggodhwani

**Comment by aashimgarg** [comment]
![Screenshot from 2022-11-22 16-57-09](https://user-images.githubusercontent.com/55639487/203761399-92f7623f-d7d2-4d6b-b372-0e13d0833085.png)
