### ISSUE TITLE
(St), (Sc) not capitalised in constituency homepage

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#16]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/64309749/198584028-d44cdcfe-cf02-48fa-a238-9feaa33f0a96.png">

**Comment by tauseefsshah** [comment]
@arunsud I had fixed this earlier and it's working for me. Can you please check again.

**Comment by arunsud** [comment]
Thanks @tauseefsshah It looks fixed now. I checked a few constituencies. Closing.
