### ISSUE TITLE
Fix explorer view direct access

### ISSUE THREAD

**Issue by tauseefsshah** [cbgaindia/constituency-frontend#23]
When scheme explorer view is visited in following order, it breaks:
1) Homepage
2) Select any state and constituency and go the constituency page
3) Select Explorer section
4) Select scheme

It breaks after the scheme is selected and it only breaks for schemes that don't have any data.

![image](https://user-images.githubusercontent.com/63847553/202468750-bc054538-7061-400f-8eee-51fd67c68b14.png)

It should be disabled to to select schemes that don't have any data.
Thoughts @arunsud @samwhocodes @gggodhwani

**Comment by aashimgarg** [comment]
This is fixed! Can you please recheck @tauseefsshah
