### ISSUE TITLE
Data not showing up on Scheme Performance Snapshot

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#24]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/64309749/202628345-abffe55e-19ad-49b4-bc53-39ea675aefb9.png">

@tauseefsshah can explain the issue better.

**Comment by tauseefsshah** [comment]
The data is present in the back-end on CKAN but it's not showing on the page for schemes for some reason. @aashimgarg

**Comment by aashimgarg** [comment]
![Screenshot from 2022-11-21 14-29-31](https://user-images.githubusercontent.com/55639487/203008275-905013e7-ed81-4221-9d91-d8d5cd617186.png)

**Comment by aashimgarg** [comment]
Some schemes do not have the Bihar data ( so I removed them ) and the remaining ones do not have data for this indicator and fiscal year cc @tauseefsshah @arunsud

**Comment by tauseefsshah** [comment]
@aashimgarg The issue is with data now showing. If you check the data object the data was present there, it was just not showing. And the default behavior of the page had this already that only those schemes were there that had data for any fiscal year / any indicator.

**Comment by aashimgarg** [comment]
Fixed!
