### ISSUE TITLE
Page view breaking for scheme state view

### ISSUE THREAD

**Issue by tauseefsshah** [cbgaindia/constituency-frontend#31]
Steps to reproduce:

1. From homepage in vidhan selector select `Bihar` state and `Agiaon (SC)` constitutency
2.  Go to explorer view
3. Select `MGNREGS` scheme
4. Select State View (This is where it breaks and throws application error)

Reported by @samwhocodes

**Comment by aashimgarg** [comment]
This is fixed! @tauseefsshah can you please recheck
