### ISSUE TITLE
UP alignment needs to be change from centre to left in the state selector

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#34]
<img width="277" alt="Screenshot 2022-11-25 at 8 20 59 AM" src="https://user-images.githubusercontent.com/67921422/203891598-14e6a09a-3438-448e-84b5-f175d17b0959.png">

**Comment by tauseefsshah** [comment]
@samwhocodes It's aligned correctly. I tested on Mozilla, Chrome and Edge. Can you please confirm? And please let me know the browser you checked on.
![image](https://user-images.githubusercontent.com/63847553/204120913-4975ed05-448a-4e7f-96ca-4abd24cccc03.png)
