### ISSUE TITLE
Name of some constituencies are in lower case on map view, it needs to bee changed to title case

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#35]
<img width="427" alt="Screenshot 2022-11-25 at 9 57 49 AM" src="https://user-images.githubusercontent.com/67921422/203901412-77466aac-c95f-404c-a2ea-c986a5676e6e.png">

**Comment by tauseefsshah** [comment]
@PixeledCode Please review this pull request and merge into `main` so we can close this issue.
