### ISSUE TITLE
Homepage | Constituencies not in alphabetical order; (SC) (ST) with improper capitalisation

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#4]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/64309749/197116584-60ba043f-0718-4379-b257-d9ed9d7dc033.png">

The source [spreadsheet](https://docs.google.com/spreadsheets/d/1Sh5iC8CjdbcurfUMR5-TTCh27FMOcvEXi4iAzBy29Fg/edit#gid=150576915) contains the list of all constituencies in alphabetical order. Might be better to present it that way in the drop-down. 

Additionally, a few constituencies with `(SC)` or `(ST)` against their name have *improper capitalisation*. They currently appear as `(Sc)` or `(St)`.

**Comment by PixeledCode** [comment]
<img width="419" alt="Screenshot 2022-10-24 at 10 46 17 AM" src="https://user-images.githubusercontent.com/22215209/197453131-6459d430-6ddf-48f0-888a-b96c2a9f4f91.png">

In files, some constituencies have upper case, and others have lower case capitalization. Are we only keeping the ones that are uppercase as uppercase? 

Also, @tauseefsshah, The JSON created only has lowercase in them. Please look into that

**Comment by PixeledCode** [comment]
> The source [spreadsheet](https://docs.google.com/spreadsheets/d/1Sh5iC8CjdbcurfUMR5-TTCh27FMOcvEXi4iAzBy29Fg/edit#gid=150576915) contains the list of all constituencies in alphabetical order

I don't have access to the link here but the one uploaded in CKAN are in constituency code order

**Comment by tauseefsshah** [comment]
@samwhocodes Let me know if I should just Capitalize the words or maybe uppercase them.

**Comment by arunsud** [comment]
@tauseefsshah - the `(SC)` and `(ST)` that comes in brackets should be capitalised. I'd let @samwhocodes decide whether the entire constituency name should be capitalised. cc: @PixeledCode
