### ISSUE TITLE
Homepage | Trending Search

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#5]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/64309749/197116997-dcd5d72d-c216-45ad-b7c5-0bf6e13efebc.png">

- There seems to be a spacing issue between the constituency's name and state's name. Also, <u>`Allahabad , Uttar Pradesh`</u> seems to my eyes as two separate options. Is there a better way to mention the constituency and state together so that it feels like a single option? 
- One of the links is not working, leads to a `500 Internal Server Error` page, others are redirecting to different constituencies, not the ones mentioned in the text.

**Comment by PixeledCode** [comment]
these were supposed to be placeholder text. Can you share the text and link for the trending search part? @arunsud
