### ISSUE TITLE
Change in Default Indicator and Indicator Sequence 

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#52]
- Default indicator to be changed as Budget Utilisation
- Sequences of the common indicators should be like as: Budget Allocation; Opening Balance; Funds Released; Budget Utilisation and Unspent Balance
<img width="624" alt="Screenshot 2022-12-29 at 8 56 05 AM" src="https://user-images.githubusercontent.com/67921422/209901405-c7d11fd1-c666-41bd-a342-3a088029af20.png">

**Comment by PixeledCode** [comment]
Default indicator changed to Budget Utilisation

**Comment by tauseefsshah** [comment]
Indicators sequence changed
