### ISSUE TITLE
Change Scheme Sequence

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#53]
Sequence of Schemes view should be MGNREGS, PMAY-G, SBM-G, PMMVY, MDM, ICDS, PMFBY-R, PMFBY-K, PM-KISAN, NSAP, NHM, SmSA, SBM-U

**Comment by tauseefsshah** [comment]
Sequence changed in the json but still showing in unordered serial on the platform. @PixeledCode 
This is for https://constituency.openbudgetsindia.org/bihar/lok/9
![image](https://user-images.githubusercontent.com/63847553/210185496-744bb900-1a43-4e92-b3f8-1cd67081b513.png)
