### ISSUE TITLE
Changing Back Default option

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#54]
If someone is on the map view page, an they click back, they the diverted to the main landing page of the constituency dashboard, however they should either just go back to one step or at max to the scheme snapshot page

**Comment by tauseefsshah** [comment]
Also the logo for schemes is not changing from the map view when we change the scheme from the dropdown.
Reported By @samwhocodes

**Comment by PixeledCode** [comment]
Fixed
