### ISSUE TITLE
Disparity in data on scheme snapshot vs map view

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#55]
Data for scheme visible on the map view is somehow not visible on scheme performance snapshot - Bothe these view are taking data from different places

**Comment by tauseefsshah** [comment]
@PixeledCode The correct data is coming from both the json file and csv, i cross checked but it's still not showing on scheme snapshot while it;s working fine on data explorer and map view. I checked the slug it's same. The schme is `SBMU`, year is `2019-20` in this case.

https://constituency.openbudgetsindia.org/bihar/lok/9?scheme=nhm&indicator=

json
![image](https://user-images.githubusercontent.com/63847553/210185760-07e87de7-2e9d-43fd-8346-eefac9fd3a33.png)

csv
![image](https://user-images.githubusercontent.com/63847553/210185813-6ba8080d-fdbf-4c33-9235-c0b7cefadc44.png)

scheme snapshot
![image](https://user-images.githubusercontent.com/63847553/210185783-c6101b0a-b20a-4f82-b469-d90367d4dc87.png)

data explorer
![image](https://user-images.githubusercontent.com/63847553/210185824-24917471-94f4-487f-a65e-099458bb9dec.png)

**Comment by arunsud** [comment]
Fixed.
