### ISSUE TITLE
Map view breaking for some scheme. Link in desciption

### ISSUE THREAD

**Issue by tauseefsshah** [cbgaindia/constituency-frontend#56]
https://constituency.openbudgetsindia.org/odisha/vidhan/128?scheme=pmfby_kharif&indicator=budget-utilisation

Reported By @samwhocodes

**Comment by PixeledCode** [comment]
Problem is with the file in CKAN

**Comment by tauseefsshah** [comment]
@PixeledCode CKAN file has data in same format for all the constituencies and all the schemes. It's only breaking for selective schemes
![image](https://user-images.githubusercontent.com/63847553/210185935-3d785703-6c73-4954-b082-238442f23ea4.png)

**Comment by PixeledCode** [comment]
fixed
