### ISSUE TITLE
Footer | Additions and Deletions

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#6]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/64309749/197117669-44d0d54f-f8c3-4502-a91b-cf57b077c309.png">

Need to add Assam Budget Explorer 2022-23, Odisha Budget Explorer 2022-23 (when it becomes added to OBI homepage, but it can be kept ready in dev branch), Budget Forum and Budget Basics are not there in the footer (even in OBI as well). So we have to add them as well.

**Comment by PixeledCode** [comment]
Can you provide text and links that need to be added

**Comment by arunsud** [comment]
[Assam Budget Explorer 2022-23](https://assam.openbudgetsindia.org/)

[Assam Budget Explorer 2021-22](https://assam2021.openbudgetsindia.org/)

[Odisha Budget Explorer 2022-23](https://odisha.openbudgetsindia.org/) - not yet live

[Budget Forum](https://forum.openbudgetsindia.org/)

[Budget Basics](https://budgetbasics.openbudgetsindia.org/)

**Comment by PixeledCode** [comment]
@aashimgarg can you do and close this?

**Comment by tauseefsshah** [comment]
@arunsud `Budget Forum` and `Budget Basics` go under `OBI Platform` section and rest under `Dashboards` correct?

**Comment by arunsud** [comment]
Correct. Odisha can go live now. OBI homepage will be updated later. If you can [take it up](https://chat.civicdatalab.in/group/project-obi-phase-ii?msg=YYcpLtWnaQwrq96RJ) since Abhinav is busy, that'd be great.
