### ISSUE TITLE
Comparison issue + constituencies showing up multiple times in the search box

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#62]
![error in comparison view](https://user-images.githubusercontent.com/64309749/211462637-43738beb-be31-4372-9d05-983a20760c1a.gif)

**Comment by arunsud** [comment]
Gorakhpur showing up multiple times, and then application error comes when clicking.

**Comment by PixeledCode** [comment]
fixed the crashing, working on multiple enteries

**Comment by PixeledCode** [comment]
fixed in latest
