### ISSUE TITLE
No indication that the indicator list is scrollable

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#64]
![image](https://user-images.githubusercontent.com/64309749/211463166-edb29389-e892-462b-adc7-d7f8b74f6da2.png)

Indicators are getting cutoff

**Comment by PixeledCode** [comment]
Which browser are you using @arunsud? Usually, the browser shows a scrollbar on the right side when it is scrollable.

**Comment by PixeledCode** [comment]
issue was for safari browser, fixed
