### ISSUE TITLE
Several constituency pages not opening

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#8]
![no-data-consti](https://user-images.githubusercontent.com/64309749/198504534-9cf44657-c041-463f-8fb0-9c34a4468db5.gif)

Several constituencies are showing the error `404 | Page not found`. 

Is there any issue in the front-end or should we check the uploaded data along with @samwhocodes and @tauseefsshah

**Comment by tauseefsshah** [comment]
@PixeledCode Can you please confirm if the issue is in front-end or data

**Comment by PixeledCode** [comment]
spelling mistake in remarks file is causing this
