### ISSUE TITLE
Spelling error 

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#80]
Spelling of constituency needs to be corrected in the top left corner after vidhan sabha and lok sabha
<img width="966" alt="Screenshot 2023-02-16 at 11 28 34 AM" src="https://user-images.githubusercontent.com/67921422/219283301-ea862a33-f71b-48ad-a160-4faca87afd13.png">
<img width="1005" alt="Screenshot 2023-02-16 at 11 40 23 AM" src="https://user-images.githubusercontent.com/67921422/219283324-3d754820-17d4-4b01-b23c-6807708dbe44.png">

**Comment by aashimgarg** [comment]
Fixed!
