### ISSUE TITLE
Scheme Snapshot view | Indicator Unit wrong

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/constituency-frontend#87]
![image](https://user-images.githubusercontent.com/64309749/220863051-51fcf2ea-7ed9-42c5-a0ad-bc4290fb0cdc.png)

Extent of utilisation's unit is `%`. Shows up as `Cr` in the the scheme snapshot view. Unit it correct in the explorer page where it's reading off of the metadata sheet as `in per cent`.

**Comment by aashimgarg** [comment]
Fixed!
