### ISSUE TITLE
Extent of Utilisation should be in % on scheme performance snapshot page

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#95]
<img width="975" alt="Screenshot 2023-02-23 at 10 57 02 PM" src="https://user-images.githubusercontent.com/67921422/220983674-a757b2be-4f16-4084-b978-971eb22142a3.png">

For indicator "extent of utilisation" the unit is %, it needs to be changed

**Comment by PixeledCode** [comment]
fixed
