### ISSUE TITLE
"Zero" in Table View (It should be NA, as in data it is NA)

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#99]
<img width="953" alt="Screenshot 2023-02-24 at 7 37 24 PM" src="https://user-images.githubusercontent.com/67921422/221198842-fb65c2ed-f3bd-4707-8e9d-8d8b1e91418c.png">

**Comment by PixeledCode** [comment]
fixed

**Comment by PixeledCode** [comment]
fixed
